version: 0.0
os: linux

files:
  - source: /start_container.sh
    destination: /home/ubuntu/app/scripts/

hooks:
  - ApplicationStart:
      location: start_container.sh

      workingDirectory: /home/ubuntu/app/scripts/

      timeout: 300

      runas: root