services:
  db:
    image: postgres:15
    restart: unless-stopped
    container_name: dyslexia_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - dyslexia_db:/var/lib/postgresql/data
  app:
    image: openjdk:17-slim
    container_name: dyslexia_app
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app/app.jar
      - ./uploads:/root/app/uploads
      - ./logs:/var/log/dyslexia-app
    depends_on:
      - db
    restart: unless-stopped
    command: ["java", "-jar", "/app/app.jar"]

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    restart: unless-stopped
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    image: kibana:8.9.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: elastic/filebeat:8.9.0
    container_name: filebeat
    user: root
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/dyslexia-app:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  dyslexia_db:
  es-data:

