services:
  app:
    image: openjdk:17-slim
    container_name: dyslexia_app
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app/app.jar
      - ./uploads:/root/app/uploads
      - ./logs:/var/log/dyslexia-app
    depends_on:
      - db
    restart: unless-stopped
    command: [ "java", "-jar", "/app/app.jar" ]