services:
  app:
    image: ${APP_IMAGE_URI}
    container_name: dyslexia_app
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/root/app/uploads
      - ./logs:/var/log/dyslexia-app
    depends_on:
      - db
    restart: unless-stopped