spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 100
  jwt:
    secret: ${JWT_SECRET}

kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}

server:
  servlet:
    context-path: /api
  port: 8080
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.dyslexia.dyslexia.controller
  default-produces-media-type: application/json
  paths-to-match:
    - /**
  show-actuator: true