#name: Deploy to Server
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Check out code
#        uses: actions/checkout@v2
#
#      - name: Build project
#        run: |
#          ./gradlew clean build -x test
#
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#      - name: Copy JAR file to Server
#        run: |
#          scp -o StrictHostKeyChecking=no ./build/libs/dyslexia-0.0.1-SNAPSHOT.jar hbnu@${{ secrets.DYSLEXIA_HOST }}:/home/hbnu/app/app.jar
#          scp -o StrictHostKeyChecking=no ./docker-compose.yml hbnu@${{ secrets.DYSLEXIA_HOST }}:/home/hbnu/app/docker-compose.yml
#          scp -o StrictHostKeyChecking=no ./Makefile hbnu@${{ secrets.DYSLEXIA_HOST }}:/home/hbnu/app/Makefile
#
#      - name: Restart Docker on Server
#        run: |
#          ssh -o StrictHostKeyChecking=no hbnu@${{ secrets.DYSLEXIA_HOST }} << 'EOF'
#          cd /home/hbnu/app
#          make re
#          EOF